/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TIARA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class LaporanProduk extends javax.swing.JFrame {
    
        PreparedStatement pst = null;
        ResultSet rs = null;
    /**
     * Creates new form LaporanProduk
     */
    public LaporanProduk() {
        initComponents();
        fetchDataTabelProduk();
    }
    public ArrayList<ProdukList> produkList() {
        ArrayList<ProdukList> produkList = new ArrayList<>();
        try {
            Connection con = connectionHelper.getConnection();
            String sql = "SELECT data_produk.id_produk,data_produk.id_barang,data_produk.nama_produk,data_produk.harga_asli,data_produk.produk_masuk FROM data_produk ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            ProdukList produk;
            while (rs.next()) {
                ////// urutan tidak sama////////
                produk = new ProdukList(rs.getInt("id_produk"), rs.getInt("id_barang"), rs.getInt("harga_asli"),rs.getInt("produk_masuk"),rs.getString("nama_produk"));
                produkList.add(produk);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        return produkList;
    }

    private void fetchDataTabelProduk() {
        ArrayList<ProdukList> list = produkList();
        DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
         
            row[0] = list.get(i).getId_produk();
            row[1] = list.get(i).getNama_produk();
            row[2] = list.get(i).getHarga_asli();
            row[3] = list.get(i).getProduk_masuk();
            
            

            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        saveBtnProduk = new javax.swing.JButton();
        deleteBtnProduk = new javax.swing.JButton();
        updateBtnProduk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        namaProduktxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jmlprodukmasuktxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        IDProduktxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hargaAslitxt = new javax.swing.JTextField();
        refreshBtnProduk = new javax.swing.JButton();
        resetBtnProduk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(0, 204, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(597, 340));

        judulLabel1.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        judulLabel1.setText("Laporan Produk");
        judulLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nama Produk", "Harga Asli", "Jml Produk Masuk"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelProduk);

        saveBtnProduk.setText("Save");
        saveBtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnProdukActionPerformed(evt);
            }
        });

        deleteBtnProduk.setText("Delete");
        deleteBtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnProdukActionPerformed(evt);
            }
        });

        updateBtnProduk.setText("Update");
        updateBtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnProdukActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel7.setText("ID Produk:");

        namaProduktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaProduktxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel9.setText("DATA PRODUK");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel10.setText("Harga Asli :");

        jmlprodukmasuktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlprodukmasuktxtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel11.setText("Jumlah produk masuk :");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel12.setText("Nama Produk:");

        refreshBtnProduk.setText("Refresh");
        refreshBtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnProdukActionPerformed(evt);
            }
        });

        resetBtnProduk.setText("Reset");
        resetBtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(resetBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(saveBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IDProduktxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(hargaAslitxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlprodukmasuktxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaProduktxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(refreshBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtnProduk)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel9)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDProduktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(namaProduktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hargaAslitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jmlprodukmasuktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnProdukActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            //query insert data ke dalam database mysql
            pst = con.prepareStatement("INSERT INTO data_produk (id_produk, id_barang, nama_produk,harga_asli,produk_masuk) VALUES(?,?,?,?,?)");
            //validasi ketika textField kosong

            if (IDProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID produk tidak boleh kosong");
            } else if (namaProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama produk tidak boleh kosong");
            }else if (hargaAslitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "harga asli tidak boleh kosong");
            } else if (jmlprodukmasuktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "jumlah produk masuk tidak boleh kosong");
            }   else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, IDProduktxt.getText());              
                pst.setString(3, namaProduktxt.getText());
                pst.setString(4, hargaAslitxt.getText());
                pst.setString(5, jmlprodukmasuktxt.getText());
                pst.setString(2, IDProduktxt.getText());
                
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                IDProduktxt.setText("");
                namaProduktxt.setText("");
                hargaAslitxt.setText("");
                jmlprodukmasuktxt.setText("");
                
                

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Input Berhasil");

            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnProdukActionPerformed

    private void namaProduktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaProduktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProduktxtActionPerformed

    private void jmlprodukmasuktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlprodukmasuktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlprodukmasuktxtActionPerformed

    private void refreshBtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnProdukActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
        model.setRowCount(0);
        fetchDataTabelProduk();
    }//GEN-LAST:event_refreshBtnProdukActionPerformed

    private void resetBtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnProdukActionPerformed
        // TODO add your handling code here:
        IDProduktxt.setText("");
        namaProduktxt.setText("");
        hargaAslitxt.setText("");
        jmlprodukmasuktxt.setText("");
        
        
    }//GEN-LAST:event_resetBtnProdukActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        // TODO add your handling code here:
        int i = tabelProduk.getSelectedRow();
        TableModel model = tabelProduk.getModel();
        IDProduktxt.setText(model.getValueAt(i, 0).toString());
        namaProduktxt.setText(model.getValueAt(i, 1).toString());      
        hargaAslitxt.setText(model.getValueAt(i, 2).toString());
        jmlprodukmasuktxt.setText(model.getValueAt(i, 3).toString());
        

    }//GEN-LAST:event_tabelProdukMouseClicked

    private void updateBtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnProdukActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = connectionHelper.getConnection();
            int row = tabelProduk.getSelectedRow();
            String value = (tabelProduk.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE data_produk SET id_produk=?, nama_produk=?, harga_asli=?, produk_masuk=? WHERE id_produk=" + value;
            if (IDProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID produk tidak boleh kosong");
            } else if (namaProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama produk tidak boleh kosong");
            } else if (hargaAslitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "harga asli tidak boleh kosong");
            } else if (jmlprodukmasuktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "jumlah produk masuk tidak boleh kosong");
            }  else {
                pst = con.prepareStatement(sql);
                pst.setString(1, IDProduktxt.getText());
                pst.setString(2, namaProduktxt.getText());
                pst.setString(3, hargaAslitxt.getText());
                pst.setString(4, jmlprodukmasuktxt.getText());
                
               
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
                model.setRowCount(0);
                fetchDataTabelProduk();
                IDProduktxt.setText("");
                namaProduktxt.setText("");
                hargaAslitxt.setText("");
                jmlprodukmasuktxt.setText("");
                
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih baris dulu");
        }
    }//GEN-LAST:event_updateBtnProdukActionPerformed

    private void deleteBtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnProdukActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            int row = tabelProduk.getSelectedRow();
            String value = (tabelProduk.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM data_produk WHERE id_produk=" + value;
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
            model.setRowCount(0);
            fetchDataTabelProduk();
            JOptionPane.showMessageDialog(rootPane, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDProduktxt;
    private javax.swing.JButton deleteBtnProduk;
    private javax.swing.JTextField hargaAslitxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jmlprodukmasuktxt;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JTextField namaProduktxt;
    private javax.swing.JButton refreshBtnProduk;
    private javax.swing.JButton resetBtnProduk;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtnProduk;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JButton updateBtnProduk;
    // End of variables declaration//GEN-END:variables
}
