/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TIARA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class LaporanTransaksi extends javax.swing.JFrame {
    
    // copy 1
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LaporanTransaksi
     */
    public LaporanTransaksi() {
        initComponents();
        fetchDataTransaksi();
    }
    
    // copy 2
    public ArrayList<TransaksiList> transaksiList() {
        ArrayList<TransaksiList> transaksiList = new ArrayList<>();
        try {
            Connection con = connectionHelper.getConnection();
            String sql = "SELECT data_transaksi.id_transaksi,data_transaksi.id_barang,data_transaksi.idRiwayat_hutang,data_transaksi.id_pembeli,data_transaksi.jumlah_pembayaran,data_transaksi.tgl_pembayaran FROM data_transaksi ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            TransaksiList riwayathutang;
            while (rs.next()) {
                riwayathutang = new TransaksiList(rs.getInt("id_transaksi"), rs.getInt("id_barang"), rs.getInt("id_pembeli"), rs.getInt("idRiwayat_hutang"), rs.getInt("jumlah_pembayaran"),rs.getString("tgl_pembayaran"));
                transaksiList.add(riwayathutang);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        return transaksiList;
    }
    // copy 3
    private void fetchDataTransaksi() {
        ArrayList<TransaksiList> list = transaksiList();
        DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId_transaksi();
            row[1] = list.get(i).getJumlah_pembayaran();
            row[2] = list.get(i).getTgl_pembayaran();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        saveBtnTransaksi = new javax.swing.JButton();
        deleteBtnTransaksi = new javax.swing.JButton();
        updateBtnTransaksi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jmlTransaksitxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        IDTransaksitxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        refreshBtnTransaksi = new javax.swing.JButton();
        resetBtnTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(0, 204, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(597, 340));

        judulLabel1.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        judulLabel1.setText("Laporan Transaksi");
        judulLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Jumlah Transaksi", "Tanggal Pembayaran"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelTransaksi);

        saveBtnTransaksi.setText("Save");
        saveBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnTransaksiActionPerformed(evt);
            }
        });

        deleteBtnTransaksi.setText("Delete");
        deleteBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnTransaksiActionPerformed(evt);
            }
        });

        updateBtnTransaksi.setText("Update");
        updateBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnTransaksiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel7.setText("ID Transaksi :");

        jmlTransaksitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlTransaksitxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel9.setText("DATA TRANSAKSI");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel12.setText("Jumlah Transaksi :");

        refreshBtnTransaksi.setText("Refresh");
        refreshBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnTransaksiActionPerformed(evt);
            }
        });

        resetBtnTransaksi.setText("Reset");
        resetBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(refreshBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtnTransaksi)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(resetBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDTransaksitxt)
                            .addComponent(jmlTransaksitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel9)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDTransaksitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jmlTransaksitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void saveBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnTransaksiActionPerformed
        // TODO add your handling code here:
        // copy 4
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-dd-mm");
        try {
            Connection con = connectionHelper.getConnection();
            //query insert data ke dalam database mysql, kurang tgl pembelian tipe date
            pst = con.prepareStatement("INSERT INTO data_transaksi (id_transaksi,id_barang,idRiwayat_hutang,id_pembeli,jumlah_pembayaran,tgl_pembayaran) VALUES(?,?,?,?,?,?)");
            //validasi ketika textField kosong

            if (IDTransaksitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Transaksi tidak boleh kosong");
            } else if (jmlTransaksitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jumlah Transaksi tidak boleh kosong");
            } 
            else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, IDTransaksitxt.getText());
                pst.setString(2, IDTransaksitxt.getText());
                pst.setString(3, IDTransaksitxt.getText());
                pst.setString(4, IDTransaksitxt.getText());
                pst.setString(5, jmlTransaksitxt.getText());
                pst.setString(6, formatter.format(date));
                
                
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                IDTransaksitxt.setText("");
                jmlTransaksitxt.setText("");
                

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Input Berhasil");

            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnTransaksiActionPerformed

    private void jmlTransaksitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlTransaksitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlTransaksitxtActionPerformed

    private void refreshBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnTransaksiActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        model.setRowCount(0);
        fetchDataTransaksi();
    }//GEN-LAST:event_refreshBtnTransaksiActionPerformed

    private void resetBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBtnTransaksiActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
        int i = tabelTransaksi.getSelectedRow();
        TableModel model = tabelTransaksi.getModel();
        IDTransaksitxt.setText(model.getValueAt(i, 0).toString());
        jmlTransaksitxt.setText(model.getValueAt(i, 1).toString());
        
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void updateBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnTransaksiActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = connectionHelper.getConnection();
            int row = tabelTransaksi.getSelectedRow();
            String value = (tabelTransaksi.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE data_transaksi SET id_transaksi=?,jumlah_pembayaran=?, tgl_pembayaran=? WHERE id_transaksi=" + value;
            if (IDTransaksitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID barang tidak boleh kosong");
            } else if (jmlTransaksitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama produk tidak boleh kosong");
            }  else {
                pst = con.prepareStatement(sql);
                pst.setString(1, IDTransaksitxt.getText());
                pst.setString(2, jmlTransaksitxt.getText());
                
               
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
                model.setRowCount(0);
                fetchDataTransaksi();
                IDTransaksitxt.setText("");
                jmlTransaksitxt.setText("");
                
               
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih baris dulu");
        }
    }//GEN-LAST:event_updateBtnTransaksiActionPerformed

    private void deleteBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnTransaksiActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            int row = tabelTransaksi.getSelectedRow();
            String value = (tabelTransaksi.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM data_transaksi WHERE id_transaksi=" + value;
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
            model.setRowCount(0);
            fetchDataTransaksi();
            JOptionPane.showMessageDialog(rootPane, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTransaksitxt;
    private javax.swing.JButton deleteBtnTransaksi;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jmlTransaksitxt;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JButton refreshBtnTransaksi;
    private javax.swing.JButton resetBtnTransaksi;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtnTransaksi;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton updateBtnTransaksi;
    // End of variables declaration//GEN-END:variables
}
