/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TIARA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class LaporanPembeli extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LaporanPembeli
     */
    public LaporanPembeli() {
         initComponents();
         fetchDataTabelPembeli();
    }
    
    public ArrayList<PembeliList> pembeliList() {
        ArrayList<PembeliList> pembeliList = new ArrayList<>();
        try {
            Connection con = connectionHelper.getConnection();
            String sql = "SELECT data_pembeli.id_pembeli,data_pembeli.nama_pembeli,data_pembeli.alamat,data_pembeli.nomor_hp FROM data_pembeli ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            PembeliList pembeli;
            while (rs.next()) {
                pembeli = new PembeliList (rs.getInt("id_pembeli"), rs.getString("nama_pembeli"),rs.getString("alamat"), rs.getString("nomor_hp"));
                pembeliList.add(pembeli);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        return pembeliList;
    }

    private void fetchDataTabelPembeli() {
        ArrayList<PembeliList> list = pembeliList();
        DefaultTableModel model = (DefaultTableModel) tabelPembeli.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId_pembeli();
            row[1] = list.get(i).getNama_pembeli();
            row[2] = list.get(i).getAlamat();
            row[3] = list.get(i).getNomor_hp();
            
           
   

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPembeli = new javax.swing.JTable();
        saveBtnPembeli = new javax.swing.JButton();
        deleteBtnPembeli = new javax.swing.JButton();
        updateBtnPembeli = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        namaPembelitxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        noHptxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        IDPembelitxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        alamattxt = new javax.swing.JTextField();
        refreshBtnPembeli = new javax.swing.JButton();
        resetBtnPembeli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rootPanel.setBackground(new java.awt.Color(0, 204, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(597, 340));

        judulLabel1.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        judulLabel1.setText("Laporan Pembeli");
        judulLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tabelPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nama ", "Alamat", "No HP/WA"
            }
        ));
        tabelPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembeliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPembeli);

        saveBtnPembeli.setText("Save");
        saveBtnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnPembeliActionPerformed(evt);
            }
        });

        deleteBtnPembeli.setText("Delete");
        deleteBtnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnPembeliActionPerformed(evt);
            }
        });

        updateBtnPembeli.setText("Update");
        updateBtnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnPembeliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel7.setText("ID Pembeli :");

        namaPembelitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPembelitxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel9.setText("DATA PEMBELI");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel10.setText("Alamat :");

        noHptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHptxtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel11.setText("No Hp / WA :");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel12.setText("Nama :");

        refreshBtnPembeli.setText("Refresh");
        refreshBtnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnPembeliActionPerformed(evt);
            }
        });

        resetBtnPembeli.setText("Reset");
        resetBtnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnPembeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(rootPanelLayout.createSequentialGroup()
                            .addComponent(resetBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(saveBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(IDPembelitxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alamattxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(noHptxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namaPembelitxt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(refreshBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtnPembeli)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel9)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDPembelitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(namaPembelitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(alamattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(noHptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnPembeliActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabelPembeli.getModel();
        model.setRowCount(0);
        fetchDataTabelPembeli();
    }//GEN-LAST:event_refreshBtnPembeliActionPerformed

    private void noHptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHptxtActionPerformed

    private void namaPembelitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPembelitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPembelitxtActionPerformed

    private void saveBtnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnPembeliActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            //query insert data ke dalam database mysql, kurang tgl pembelian tipe date
            pst = con.prepareStatement("INSERT INTO data_pembeli (id_pembeli,id_transaksi, nama_pembeli,alamat,nomor_hp) VALUES(?,?,?,?,?)");
            //validasi ketika textField kosong

            if (IDPembelitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID pembeli tidak boleh kosong");       
            } else if (namaPembelitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama pembeli tidak boleh kosong");
            }else if (alamattxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "alamat tidak boleh kosong");
            }else if (noHptxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nomor hp tidak boleh kosong");
            }   else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, IDPembelitxt.getText());
                pst.setString(2, IDPembelitxt.getText());
                pst.setString(3, namaPembelitxt.getText());
                pst.setString(4, alamattxt.getText());
                pst.setString(5, noHptxt.getText());
                
                
                
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                IDPembelitxt.setText("");
                namaPembelitxt.setText("");
                alamattxt.setText("");
                noHptxt.setText("");
                
                
                

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Input Berhasil");

            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnPembeliActionPerformed

    private void resetBtnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnPembeliActionPerformed
        // TODO add your handling code here:
                IDPembelitxt.setText("");
                namaPembelitxt.setText("");
                alamattxt.setText("");
                noHptxt.setText("");
    }//GEN-LAST:event_resetBtnPembeliActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tabelPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembeliMouseClicked
        // TODO add your handling code here:
        int i = tabelPembeli.getSelectedRow();
        TableModel model = tabelPembeli.getModel();
        IDPembelitxt.setText(model.getValueAt(i, 0).toString());
        namaPembelitxt.setText(model.getValueAt(i, 1).toString());
        alamattxt.setText(model.getValueAt(i, 2).toString());
        noHptxt.setText(model.getValueAt(i, 3).toString());
        
       
        
    }//GEN-LAST:event_tabelPembeliMouseClicked

    private void updateBtnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnPembeliActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = connectionHelper.getConnection();
            int row = tabelPembeli.getSelectedRow();
            String value = (tabelPembeli.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE data_pembeli SET id_pembeli=?, nama_pembeli=?, alamat=?, nomor_hp=?WHERE id_pembeli=" + value;
            if (IDPembelitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID pembeli tidak boleh kosong");   
            } else if (namaPembelitxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama pembeli tidak boleh kosong");
            }else if (alamattxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "alamat tidak boleh kosong");
            } else if (noHptxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nomor hp tidak boleh kosong");
            }    else {
                pst = con.prepareStatement(sql);
                pst.setString(1, IDPembelitxt.getText());
                pst.setString(2, namaPembelitxt.getText());
                pst.setString(3, alamattxt.getText());
                pst.setString(4, noHptxt.getText());
                
                
                
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabelPembeli.getModel();
                model.setRowCount(0);
                fetchDataTabelPembeli();
                IDPembelitxt.setText("");
                namaPembelitxt.setText("");
                alamattxt.setText("");
                noHptxt.setText("");
                
                
                
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih baris dulu");
        }
    }//GEN-LAST:event_updateBtnPembeliActionPerformed

    private void deleteBtnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnPembeliActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            int row = tabelPembeli.getSelectedRow();
            String value = (tabelPembeli.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM data_pembeli WHERE id_pembeli=" + value;
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tabelPembeli.getModel();
            model.setRowCount(0);
            fetchDataTabelPembeli();
            JOptionPane.showMessageDialog(rootPane, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnPembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDPembelitxt;
    private javax.swing.JTextField alamattxt;
    private javax.swing.JButton deleteBtnPembeli;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JTextField namaPembelitxt;
    private javax.swing.JTextField noHptxt;
    private javax.swing.JButton refreshBtnPembeli;
    private javax.swing.JButton resetBtnPembeli;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtnPembeli;
    private javax.swing.JTable tabelPembeli;
    private javax.swing.JButton updateBtnPembeli;
    // End of variables declaration//GEN-END:variables
}
