/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TIARA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;

public class LaporanRiwayatHutang extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form LaporanRiwayatHutang
     */
    public LaporanRiwayatHutang() {
        initComponents();
        fetchDataTabelRiwayatHutang();
    }

    public ArrayList<RiwayatHutangList> riwayathutangList() {
        ArrayList<RiwayatHutangList> riwayathutangList = new ArrayList<>();
        try {
            Connection con = connectionHelper.getConnection();
            String sql = "SELECT datariwayat_hutang.idRiwayat_hutang,datariwayat_hutang.id_barang,datariwayat_hutang.id_pembeli,datariwayat_hutang.jumlah_hutang,datariwayat_hutang.tgl_pembayaran,datariwayat_hutang.status_hutang,datariwayat_hutang.jumlahSisa_hutang FROM datariwayat_hutang ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            RiwayatHutangList riwayathutang;
            while (rs.next()) {
                riwayathutang = new RiwayatHutangList(rs.getInt("idRiwayat_hutang"), rs.getInt("id_barang"), rs.getInt("jumlah_hutang"), rs.getInt("id_pembeli"), rs.getInt("jumlahSisa_hutang"), rs.getString("status_hutang"), rs.getString("tgl_pembayaran"));
                riwayathutangList.add(riwayathutang);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        return riwayathutangList;
    }

    private boolean validateInput() throws SQLException {
        boolean isCompleted = false;
        Riwayathutangcoba statushutang = new Riwayathutangcoba();

        if (lunasRadioBtn.isSelected()) {
            statushutang.setStatus_hutang(lunasRadioBtn.getText());
            isCompleted = true;
        } else if (belumlunasRadioBtn.isSelected()) {
            statushutang.setStatus_hutang(belumlunasRadioBtn.getText());
            isCompleted = true;
        } else if (belumbyrRadioBtn.isSelected()) {
            statushutang.setStatus_hutang(belumbyrRadioBtn.getText());
            isCompleted = true;
        }

        return true;
    }

    private void fetchDataTabelRiwayatHutang() {
        ArrayList<RiwayatHutangList> list = riwayathutangList();
        DefaultTableModel model = (DefaultTableModel) tabelRiwayatHutang.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getIdRiwayat_hutang();
            row[1] = list.get(i).getJumlah_hutang();
            row[2] = list.get(i).getTgl_pembayaran();
            row[3] = list.get(i).getStatus_hutang();
            row[4] = list.get(i).getJumlahSisa_hutang();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRiwayatHutang = new javax.swing.JTable();
        saveBtnHutang = new javax.swing.JButton();
        deleteBtnHutang = new javax.swing.JButton();
        updateBtnHutang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Jumlahtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        IDRiwayatHutangtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sisaHutangtxt = new javax.swing.JTextField();
        refreshBtnHutang = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        resetBtnHutang = new javax.swing.JButton();
        lunasRadioBtn = new javax.swing.JRadioButton();
        belumlunasRadioBtn = new javax.swing.JRadioButton();
        belumbyrRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(0, 204, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(597, 340));

        judulLabel1.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        judulLabel1.setText("Laporan Riwayat Hutang");
        judulLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        tabelRiwayatHutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Jumlah", "Tanggal Bayar", "Status Hutang", "Sisa Hutang"
            }
        ));
        tabelRiwayatHutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRiwayatHutangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRiwayatHutang);

        saveBtnHutang.setText("Save");
        saveBtnHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnHutangActionPerformed(evt);
            }
        });

        deleteBtnHutang.setText("Delete");
        deleteBtnHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnHutangActionPerformed(evt);
            }
        });

        updateBtnHutang.setText("Update");
        updateBtnHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnHutangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel7.setText("ID Riwayat Hutang :");

        Jumlahtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahtxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel9.setText("DATA RIWAYAT HUTANG");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel12.setText("Jumlah :");

        refreshBtnHutang.setText("Refresh");
        refreshBtnHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnHutangActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel13.setText("Status Hutang :");

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel14.setText("Sisa Hutang :");

        resetBtnHutang.setText("Reset");
        resetBtnHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnHutangActionPerformed(evt);
            }
        });

        lunasRadioBtn.setText("Lunas");
        lunasRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunasRadioBtnActionPerformed(evt);
            }
        });

        belumlunasRadioBtn.setText("Belum Lunas");

        belumbyrRadioBtn.setText("Belum Dibayar");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(refreshBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtnHutang)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                            .addGap(368, 368, 368)
                            .addComponent(saveBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rootPanelLayout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel14))
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resetBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(rootPanelLayout.createSequentialGroup()
                                                    .addComponent(lunasRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                                    .addComponent(belumlunasRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(IDRiwayatHutangtxt)
                                                .addComponent(sisaHutangtxt)
                                                .addComponent(Jumlahtxt)
                                                .addComponent(belumbyrRadioBtn)))))
                                .addComponent(jLabel13))
                            .addGap(7, 7, 7)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel9)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDRiwayatHutangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lunasRadioBtn)
                    .addComponent(belumlunasRadioBtn))
                .addGap(29, 29, 29)
                .addComponent(belumbyrRadioBtn)
                .addGap(41, 41, 41)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sisaHutangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(56, 56, 56)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnHutang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnHutangActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Connection con = connectionHelper.getConnection();
            //query insert data ke dalam database mysql, kurang tgl pembelian tipe date
            pst = con.prepareStatement("INSERT INTO datariwayat_hutang (idRiwayat_hutang,id_transaksi,id_barang,id_pembeli,jumlah_hutang,tgl_pembayaran,jumlahSisa_hutang) VALUES(?,?,?,?,?,?,?)");
            //validasi ketika textField kosong

            if (IDRiwayatHutangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Riwayat Hutang tidak boleh kosong");
            } else if (Jumlahtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "jumlah hutang tidak boleh kosong");
            } else if (sisaHutangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "sisa hutang tidak boleh kosong");
            } else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, IDRiwayatHutangtxt.getText());
                pst.setString(2, IDRiwayatHutangtxt.getText());
                pst.setString(3, IDRiwayatHutangtxt.getText());
                pst.setString(4, IDRiwayatHutangtxt.getText());
                pst.setString(5, Jumlahtxt.getText());
                pst.setString(6, formatter.format(date));
                //pst.setString(6, StatusComboBox.getSelectedItem());

                pst.setString(7, sisaHutangtxt.getText());

                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                IDRiwayatHutangtxt.setText("");
                Jumlahtxt.setText("");
                sisaHutangtxt.setText("");

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Input Berhasil");

            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnHutangActionPerformed

    private void JumlahtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahtxtActionPerformed

    private void refreshBtnHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnHutangActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelRiwayatHutang.getModel();
        model.setRowCount(0);
        fetchDataTabelRiwayatHutang();
    }//GEN-LAST:event_refreshBtnHutangActionPerformed

    private void resetBtnHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnHutangActionPerformed
        // TODO add your handling code here:
        IDRiwayatHutangtxt.setText("");
        Jumlahtxt.setText("");
        sisaHutangtxt.setText("");
    }//GEN-LAST:event_resetBtnHutangActionPerformed

    private void tabelRiwayatHutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRiwayatHutangMouseClicked
        // TODO add your handling code here:
        int i = tabelRiwayatHutang.getSelectedRow();
        TableModel model = tabelRiwayatHutang.getModel();
        IDRiwayatHutangtxt.setText(model.getValueAt(i, 0).toString());
        Jumlahtxt.setText(model.getValueAt(i, 1).toString());
        sisaHutangtxt.setText(model.getValueAt(i, 2).toString());

    }//GEN-LAST:event_tabelRiwayatHutangMouseClicked

    private void updateBtnHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnHutangActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = connectionHelper.getConnection();
            int row = tabelRiwayatHutang.getSelectedRow();
            String value = (tabelRiwayatHutang.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE datariwayat_hutang SET idRiwayat_hutang=?, jumlah_hutang=?, jumlahSisa_hutang=? WHERE idRiwayat_hutang=" + value;
            if (IDRiwayatHutangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Riwayat Hutang tidak boleh kosong");
            } else if (Jumlahtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jumlah Hutang tidak boleh kosong");
            } else if (sisaHutangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sisa Hutang tidak boleh kosong");
            } else {
                pst = con.prepareStatement(sql);
                pst.setString(1, IDRiwayatHutangtxt.getText());
                pst.setString(2, Jumlahtxt.getText());
                pst.setString(3, sisaHutangtxt.getText());

                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabelRiwayatHutang.getModel();
                model.setRowCount(0);
                fetchDataTabelRiwayatHutang();
                IDRiwayatHutangtxt.setText("");
                Jumlahtxt.setText("");
                sisaHutangtxt.setText("");

                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih baris dulu");
        }
    }//GEN-LAST:event_updateBtnHutangActionPerformed

    private void deleteBtnHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnHutangActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            int row = tabelRiwayatHutang.getSelectedRow();
            String value = (tabelRiwayatHutang.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM datariwayat_hutang WHERE idRiwayat_hutang=" + value;
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tabelRiwayatHutang.getModel();
            model.setRowCount(0);
            fetchDataTabelRiwayatHutang();
            JOptionPane.showMessageDialog(rootPane, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnHutangActionPerformed

    private void lunasRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunasRadioBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_lunasRadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanRiwayatHutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanRiwayatHutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanRiwayatHutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanRiwayatHutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanRiwayatHutang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDRiwayatHutangtxt;
    private javax.swing.JTextField Jumlahtxt;
    private javax.swing.JRadioButton belumbyrRadioBtn;
    private javax.swing.JRadioButton belumlunasRadioBtn;
    private javax.swing.JButton deleteBtnHutang;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JRadioButton lunasRadioBtn;
    private javax.swing.JButton refreshBtnHutang;
    private javax.swing.JButton resetBtnHutang;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtnHutang;
    private javax.swing.JTextField sisaHutangtxt;
    private javax.swing.JTable tabelRiwayatHutang;
    private javax.swing.JButton updateBtnHutang;
    // End of variables declaration//GEN-END:variables
}
