/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TIARA
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class LaporanBarang extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form LaporanBarang
     */
    public LaporanBarang() {
        initComponents();
        fetchDataTabelBarang();
    }

    public ArrayList<BarangList> barangList() {
        ArrayList<BarangList> barangList = new ArrayList<>();
        try {
            Connection con = connectionHelper.getConnection();
            String sql = "SELECT data_barang.id_barang,data_barang.idRiwayat_hutang,data_barang.id_produk,data_barang.id_transaksi,data_barang.nama_produk,data_barang.harga_jual,data_barang.produk_terjual,data_barang.stok_barang FROM data_barang ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            BarangList barang;
            while (rs.next()) {
                barang = new BarangList(rs.getInt("id_barang"), rs.getInt("idRiwayat_hutang"), rs.getInt("id_transaksi"), rs.getInt("id_produk"), rs.getInt("harga_jual"), rs.getInt("produk_terjual"), rs.getInt("stok_barang"), rs.getString("nama_produk"));
                barangList.add(barang);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        return barangList;
    }

    private void fetchDataTabelBarang() {
        ArrayList<BarangList> list = barangList();
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId_barang();
            row[1] = list.get(i).getNama_produk();
            row[2] = list.get(i).getHarga_jual();
            row[3] = list.get(i).getProduk_terjual();
            row[4] = list.get(i).getStok_barang();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        SaveBtnBarang = new javax.swing.JButton();
        deleteBtnBarang = new javax.swing.JButton();
        updateBtnBarang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        namaProduktxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        StokBarangtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jmlbrgkeluartxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IDBarangtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HargaJualtxt = new javax.swing.JTextField();
        refreshBtnBarang = new javax.swing.JButton();
        resetBtnBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        rootPanel.setBackground(new java.awt.Color(0, 204, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(597, 340));

        judulLabel.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        judulLabel.setText("Laporan Barang");
        judulLabel.setPreferredSize(new java.awt.Dimension(100, 50));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabelBarang.setBackground(new java.awt.Color(204, 204, 204));
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nama Produk", "Harga Jual", "Jml Produk Terjual", "Stok Barang"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        SaveBtnBarang.setText("Save");
        SaveBtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnBarangActionPerformed(evt);
            }
        });

        deleteBtnBarang.setText("Delete");
        deleteBtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnBarangActionPerformed(evt);
            }
        });

        updateBtnBarang.setText("Update");
        updateBtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnBarangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel2.setText("ID Barang :");

        namaProduktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaProduktxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel6.setText("Stok Barang :");

        jLabel1.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel1.setText("DATA BARANG");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel4.setText("Harga Jual :");

        jmlbrgkeluartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbrgkeluartxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel5.setText("Jumlah Barang Keluar :");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel3.setText("Nama Produk :");

        refreshBtnBarang.setText("Refresh");
        refreshBtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnBarangActionPerformed(evt);
            }
        });

        resetBtnBarang.setText("Reset");
        resetBtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(refreshBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtnBarang)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(resetBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jmlbrgkeluartxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HargaJualtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaProduktxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDBarangtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StokBarangtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDBarangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaProduktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(HargaJualtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jmlbrgkeluartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(StokBarangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaProduktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaProduktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProduktxtActionPerformed

    private void jmlbrgkeluartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbrgkeluartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlbrgkeluartxtActionPerformed

    private void SaveBtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnBarangActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = connectionHelper.getConnection();
            //query insert data ke dalam database mysql
            pst = con.prepareStatement("INSERT INTO data_barang (id_barang, idRiwayat_hutang,id_transaksi,id_produk, nama_produk, harga_jual, produk_terjual, stok_barang) VALUES(?,?,?,?,?,?,?,?)");
            //validasi ketika textField kosong

            if (IDBarangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID barang tidak boleh kosong");
            } else if (namaProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama produk tidak boleh kosong");
            } else if (HargaJualtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "harga jual tidak boleh kosong");
            } else if (jmlbrgkeluartxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "jumlah barang keluar tidak boleh kosong");
            } else if (StokBarangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "stok barang tidak boleh kosong");
            } else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, IDBarangtxt.getText());
                pst.setString(2, IDBarangtxt.getText());
                pst.setString(3, IDBarangtxt.getText());
                pst.setString(4, IDBarangtxt.getText());
                pst.setString(5, namaProduktxt.getText());
                pst.setString(6, HargaJualtxt.getText());
                pst.setString(7, jmlbrgkeluartxt.getText());
                pst.setString(8, StokBarangtxt.getText());
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                IDBarangtxt.setText("");
                namaProduktxt.setText("");
                HargaJualtxt.setText("");
                jmlbrgkeluartxt.setText("");
                StokBarangtxt.setText("");

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Input Berhasil");

            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_SaveBtnBarangActionPerformed

    private void refreshBtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnBarangActionPerformed
        // TODO add your handling code here: // nama tabel di desain
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        model.setRowCount(0);
        fetchDataTabelBarang();
    }//GEN-LAST:event_refreshBtnBarangActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int i = tabelBarang.getSelectedRow();
        TableModel model = tabelBarang.getModel();
        IDBarangtxt.setText(model.getValueAt(i, 0).toString());
        namaProduktxt.setText(model.getValueAt(i, 1).toString());
        HargaJualtxt.setText(model.getValueAt(i, 2).toString());
        jmlbrgkeluartxt.setText(model.getValueAt(i, 3).toString());
        StokBarangtxt.setText(model.getValueAt(i, 4).toString());

    }//GEN-LAST:event_tabelBarangMouseClicked

    private void updateBtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnBarangActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = connectionHelper.getConnection();
            int row = tabelBarang.getSelectedRow();
            String value = (tabelBarang.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE data_barang SET id_barang=?, nama_produk=?, harga_jual=?, produk_terjual=?, stok_barang=? WHERE id_barang=" + value;
            if (IDBarangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID barang tidak boleh kosong");
            } else if (namaProduktxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "nama produk tidak boleh kosong");
            } else if (HargaJualtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "harga jual tidak boleh kosong");
            } else if (jmlbrgkeluartxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "jumlah barang keluar tidak boleh kosong");
            } else if (StokBarangtxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "stok barang tidak boleh kosong");
            } else {
                pst = con.prepareStatement(sql);
                pst.setString(1, IDBarangtxt.getText());
                pst.setString(2, namaProduktxt.getText());
                pst.setString(3, HargaJualtxt.getText());
                pst.setString(4, jmlbrgkeluartxt.getText());
                pst.setString(5, StokBarangtxt.getText());
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
                model.setRowCount(0);
                fetchDataTabelBarang();
                IDBarangtxt.setText("");
                namaProduktxt.setText("");
                HargaJualtxt.setText("");
                jmlbrgkeluartxt.setText("");
                StokBarangtxt.setText("");
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih baris dulu");
        }
    }//GEN-LAST:event_updateBtnBarangActionPerformed

    private void deleteBtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnBarangActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionHelper.getConnection();
            int row = tabelBarang.getSelectedRow();
            String value = (tabelBarang.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM data_barang WHERE id_barang=" + value;
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
            model.setRowCount(0);
            fetchDataTabelBarang();
            JOptionPane.showMessageDialog(rootPane, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnBarangActionPerformed

    private void resetBtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnBarangActionPerformed
        // TODO add your handling code here:
        IDBarangtxt.setText("");
        namaProduktxt.setText("");
        HargaJualtxt.setText("");
        jmlbrgkeluartxt.setText("");
        StokBarangtxt.setText("");
    }//GEN-LAST:event_resetBtnBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HargaJualtxt;
    private javax.swing.JTextField IDBarangtxt;
    private javax.swing.JButton SaveBtnBarang;
    private javax.swing.JTextField StokBarangtxt;
    private javax.swing.JButton deleteBtnBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlbrgkeluartxt;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField namaProduktxt;
    private javax.swing.JButton refreshBtnBarang;
    private javax.swing.JButton resetBtnBarang;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton updateBtnBarang;
    // End of variables declaration//GEN-END:variables
}
